<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Noise-Busters: How to Sharpen Your Monte Carlo</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="variance_reduction_files/libs/clipboard/clipboard.min.js"></script>
<script src="variance_reduction_files/libs/quarto-html/quarto.js"></script>
<script src="variance_reduction_files/libs/quarto-html/popper.min.js"></script>
<script src="variance_reduction_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="variance_reduction_files/libs/quarto-html/anchor.min.js"></script>
<link href="variance_reduction_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="variance_reduction_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="variance_reduction_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="variance_reduction_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="variance_reduction_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Noise-Busters: How to Sharpen Your Monte Carlo</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="do-you-know-your-monte-carlo" class="level3">
<h3 class="anchored" data-anchor-id="do-you-know-your-monte-carlo">1 Do You Know Your Monte Carlo?</h3>
<p>Remember when we first met in <strong>Tutorial #1: Estimating <span class="math inline">\(\pi\)</span> with Monte Carlo</strong> — where we used a humble sampler to toss random darts, watched our estimate inch toward 3.14, and felt like statistical wizards? If you need a refresher, dust off that guide <a href="https://www.youtube.com/watch?v=p4Jj9QZFJvw">here</a> — it’s still our go‑to warm‑up.</p>
<p>But hold on to your hats, because not every problem plays nicely with our random‑point strategy.</p>
<p><em>In real‑world applications, naïve Monte Carlo can quickly morph into Monte Chaos — slow convergence, ballooning variance, and estimates that jiggle all over the place</em>.</p>
<p>In this chapter, we’ll pinpoint exactly where — and why — standard Monte Carlo hits its limits, setting the stage for our arsenal of variance‑reduction techniques.</p>
</section>
<section id="when-standard-monte-carlo-falters" class="level3">
<h3 class="anchored" data-anchor-id="when-standard-monte-carlo-falters">2.1 When Standard Monte Carlo Falters</h3>
<p>Monte Carlo is our trusty statistical workhorse — great for approximating expectations and probabilities — but every steed has its weak spots. In practice, naïve Monte Carlo can grind to a halt in two notorious scenarios:</p>
<ol type="1">
<li><p><strong>Rare‑Event Estimation</strong>. Imagine estimating: <span class="math display">\[
p = P(Z_1 + Z_2 &gt; 4),\quad Z_i \sim N(0,1),
\]</span> which only happens about 0.2% of the time. Standard Monte Carlo becomes the tortoise in a race against time: you need astronomically many samples before you accumulate enough “hits” to stop your estimate from bouncing around like a pinball. After all, the variance of the sample proportion <span class="math inline">\(Var(p^)=p(1−p)n\)</span> stays stubbornly large unless n is on the order of millions — if not billions.</p></li>
<li><p><strong>Intractable Integrals</strong>.Now let’s think about integrals without closed‑form solutions, for example: <span class="math display">\[
I=∫f(x) dP(x),
\]</span> showing up in high‑dimensional Bayesian posteriors, exotic payoff functions, or particle‑physics models. If <span class="math inline">\(f(x)\)</span> is “spiky” or the distribution <span class="math inline">\(P\)</span> wiggles in complicated ways, our random samples need to explore vast, convoluted spaces — and variance explodes.</p></li>
</ol>
<p>In both of these villains’ origin stories, naïve Monte Carlo demands so many samples that — even with parallel clusters and job schedulers — your pipeline chokes. We need both statistical <strong>and</strong> software-engineering tricks: variance-reduction and clean, reproducible code.</p>
</section>
<section id="why-so-many-samples" class="level3">
<h3 class="anchored" data-anchor-id="why-so-many-samples">2.2 Why so many samples?</h3>
<p>Because standard Monte Carlo converges at only <span class="math inline">\(O(1/\sqrt{n})\)</span>. In human terms, that means <strong>halving</strong> your error demands <strong>quadrupling</strong> the number of simulations! When your target — be it a rare‑event indicator or a jagged payoff function — carries high variance those extra samples still leave your estimates jittery for far longer than you’d like.</p>
</section>
<section id="monte-carlo-chaos-simple-example" class="level3">
<h3 class="anchored" data-anchor-id="monte-carlo-chaos-simple-example">2.3 Monte Carlo Chaos: Simple Example</h3>
<p>To see this in action, consider estimating <span class="math display">\[
p \;=\; P\bigl(Z_1 + Z_2 &gt; 4\bigr), \quad Z_i \sim N(0,1).
\]</span> Because <span class="math inline">\(Z_1 + Z_2 \sim N(0,2)\)</span>, the <strong>true</strong> probability is <span class="math display">\[
p \;=\; 1 - \Phi\!\Bigl(\frac{4}{\sqrt{2}}\Bigr)
\;\approx\; 0.00235.
\]</span></p>
<p>For this example, let’s independently run Standard MC 3 times with 100,000 sims each. We get:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  run estimate
1   1  0.00232
2   2  0.00251
3   3  0.00240</code></pre>
</div>
</div>
<p>Nice — all three runs hit the neighborhood of <span class="math inline">\(0.00235\)</span>. But don’t break out the champagne just yet. Even with <span class="math inline">\(\hat p = 0.0024\)</span> and <span class="math inline">\(n = 10^5\)</span>, the standard error is</p>
<p><span class="math display">\[
\mathrm{SE}(\hat p)
= \sqrt{\frac{\hat p\,(1 - \hat p)}{n}}
\approx 0.0001548.
\]</span></p>
<p>gives a 95 % confidence interval of</p>
<p><span class="math display">\[
\hat p \pm 1.96\,\mathrm{SE}(\hat p)
\approx 0.0024 \pm 0.0003034,
\]</span></p>
<p>or about <span class="math inline">\(\pm12.7\%\)</span> relative uncertainty.</p>
<blockquote class="blockquote">
<p>Ouch. A dozen‑percent wiggle room might sound harmless in theory, but in risk management, engineering, or physics, that’s a one‑way ticket to “unacceptable.” Decision‑makers often demand even as low as 1% before pulling the trigger.</p>
</blockquote>
<p><strong>Can I decrease my confidence interval with Monte Carlo?</strong> Yes — but prepare to pay!</p>
<ol type="a">
<li><p><em>The Four‑Times Rule</em> Standard Monte Carlo is stubbornly <span class="math inline">\(O(1/\sqrt{n})\)</span>. Recall: halving your confidence‑interval width (e.g.&nbsp;from 15% to ≈7.5%) requires <strong>quadrupling</strong> your sample size — from 100,000 to 400,000 runs — every single time you need more precision.</p></li>
<li><p><em>Practical Cost</em> Even if each trial takes only 0.001s, 100,000 simulations require about 100s of compute. Four times that is nearly <strong>7 minutes</strong> — and that’s just for one estimate. Multiply across multiple parameters or repeated runs, and your compute budget (and patience) will quickly evaporate.</p></li>
</ol>
<p>Since our toy problem is cheap to compute, we can crank up the sample size and watch both the bias and variance collapse toward the true value.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="variance_reduction_files/figure-html/plot_monte_chaos-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In the plot above (note the dash line is our true <span class="math inline">\(p\)</span>), notice:</p>
<ul>
<li>At <span class="math inline">\(n = 10^3\)</span>, the 95% CI is a <span class="math inline">\([-0.0005, 0.0065]\)</span> — and the point estimate underestimates the true <span class="math inline">\(p \approx 0.00235\)</span>.</li>
<li>At <span class="math inline">\(n = 5\times10^4\)</span>, things look steadier — still noisy though.</li>
<li>Even at <span class="math inline">\(n = 10^6\)</span>, the CI continues to shrink, illustrating that each four‑fold increase in <span class="math inline">\(n\)</span> roughly halves the interval width.</li>
</ul>
<p>This is the <span class="math inline">\(O(1/\sqrt{n})\)</span> grind: more samples yield tighter confidence intervals, but at the cost of exponentially greater computation.</p>
<p><strong>Bottom line</strong>: Standard Monte Carlo will eventually nail down your rare‑event probability — but at the cost of dramatically more samples (and more time). In the next section, we’ll unlock three variance‑reduction power tools that deliver comparable — or even better — precision with far fewer simulations:</p>
<ol type="1">
<li><p><strong>Antithetic Sampling</strong>, which pairs each random draw with its “opposite” to cancel noise;</p></li>
<li><p><strong>Control Variates</strong>, which uses an auxiliary variable with known expectation as your statistical safety net;</p></li>
<li><p><strong>Importance Sampling</strong>, which wraps your sampling distribution to focus on the most “important” regions.</p></li>
</ol>
</section>
<section id="standard-mc-as-a-baseline" class="level3">
<h3 class="anchored" data-anchor-id="standard-mc-as-a-baseline">3.1 Standard MC as a Baseline</h3>
<p>Before we unleash our variance‑reduction magic, let’s pin down our <strong>baseline</strong> — the trusty, if somewhat plodding, standard Monte Carlo with a modest <span class="math inline">\(n = 10^3\)</span>.</p>
<p>Our go‑to unbiased estimator remains <span class="math display">\[
\hat p_{\text{MC}} = \frac1n \sum_{i=1}^n \mathbf{1}\{Z_{1,i} + Z_{2,i} &gt; 4\},
\]</span></p>
<p>which carries sampling variance <span class="math display">\[
\mathrm{Var}(\hat p_{\text{MC}}) \;=\; \frac{p(1-p)}{n}.
\]</span></p>
<p>Calculating these for our previous example, we get:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Standard MC estimate: 0.005 
Sampling variance: 0.00497998 </code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>With <span class="math inline">\(n = 10^3\)</span> draws (by bottlenecking <span class="math inline">\(n\)</span> this way, we’ll really get to see how our variance‑reduction techniques calm the storm), our standard Monte Carlo doesn’t just stumble — it wildly overshoots with <span class="math inline">\(\hat p = 0.005\)</span> vs.&nbsp;the true <span class="math inline">\(p\approx0.00235\)</span>. It also rages with massive sampling variance (<span class="math inline">\(\mathrm{Var} \approx 0.00498\)</span>). It’s like trying to staple jelly to a wall—messy, unpredictable, and almost guaranteed to make a mess.</p>
</blockquote>
<p>Time to roll up our sleeves and tackle this jelly mess head‑on!</p>
</section>
<section id="antithetic-sampling" class="level3">
<h3 class="anchored" data-anchor-id="antithetic-sampling">3.2 Antithetic Sampling</h3>
<p><strong>The way it works</strong></p>
<p>Antithetic sampling constructs pairs <span class="math inline">\((U,1-U)\)</span> to induce negative correlation between paired outcomes, reducing variance. Formally, if <span class="math inline">\(Y = f(U)\)</span> and <span class="math inline">\(Y' = f(1-U)\)</span>, then averaging the pair yields: <span class="math display">\[
\mathrm{Var}\!\biggl(\frac{Y + Y'}{2}\biggr)
= \frac{1}{2}\bigl[\mathrm{Var}(Y) + \mathrm{Cov}(Y,Y')\bigr],
\]</span> and because <span class="math inline">\(\mathrm{Cov}(Y,Y') &lt; 0\)</span>, the variance of <span class="math inline">\(\tfrac{Y+Y'}{2}\)</span> is strictly less than that of a solo <span class="math inline">\(Y\)</span>.</p>
<p>Applying Antithetic Sampling to our simple example of estimating rare event with <span class="math inline">\(n = 10^3\)</span>, we get the following estimates:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Antithetic estimate: 0.003 
Sampling variance: 0.001492492 </code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>With just <span class="math inline">\(n = 10^3\)</span>, Antithetic Sampling nearly halves our estimator’s mood swings — dropping the point estimate from 0.005 down to 0.003 (much closer to the true 0.00235) and the sampling variance plummets from about <span class="math inline">\(0.00498\)</span> to <span class="math inline">\(0.00149\)</span>. Congrats, by introducing that negative correlation, we’ve effectively muted half the noise.</p>
</blockquote>
<p>Below, we repeat the same sample‑size sweep we did for Standard MC — only now our estimates come in antithetically tuned.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="variance_reduction_files/figure-html/plot_antithetic-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Comparing this Antithetic Sampling plot to our earlier Standard MC results, we immediately see two key improvements:</p>
<ol type="1">
<li><p><em>Tighter CIs at Low <span class="math inline">\(n\)</span></em>: At <span class="math inline">\(n=10^3\)</span>, Antithetic’s 95% CI spans roughly <span class="math inline">\([0.001, 0.007]\)</span>, whereas Standard MC’s CI was <span class="math inline">\([-0.0005, 0.0065]\)</span>. Even with the same sample budget, negative correlation cuts the interval width by about 14%.</p></li>
<li><p><em>Consistent Centering Around True <span class="math inline">\(p\)</span></em>: Across all <span class="math inline">\(n\)</span>, Antithetic estimates hug the true‑<span class="math inline">\(p\)</span> line more faithfully. Standard MC was liable to wander at low <span class="math inline">\(n\)</span>, but Antithetic keeps your estimate honest from the start.</p></li>
</ol>
<blockquote class="blockquote">
<p><strong>Bottom line</strong>: Antithetic Sampling delivers <strong>narrower</strong> confidence intervals at low <span class="math inline">\(n\)</span> and gives you reliable estimates with far fewer simulations — in other words, stronger precision without extra compute. Yet, it is not a silver bullet — so let’s keep exploring.</p>
</blockquote>
</section>
<section id="control-variates" class="level3">
<h3 class="anchored" data-anchor-id="control-variates">3.3 Control Variates</h3>
<p><strong>The way it works:</strong></p>
<p>Control Variates rely on an <strong>auxiliary random variable</strong> <span class="math inline">\(X\)</span> whose expectation <span class="math inline">\(\mu_X = E[X]\)</span> is known. You simulate your target <span class="math inline">\(Y\)</span> (say, the indicator <span class="math inline">\(\mathbf{1}\{Z_1+Z_2&gt;4\}\)</span>) in tandem with <span class="math inline">\(X\)</span>, then form:</p>
<p><span class="math display">\[
\hat Y_{\mathrm{CV}}
= \bar Y \;-\; \beta\,(\bar X - \mu_X),
\beta \;=\; \frac{\mathrm{Cov}(Y,\,X)}{\mathrm{Var}(X)}
\]</span> By choosing <span class="math inline">\(\beta\)</span> this way, you <strong>minimise</strong> the variance of <span class="math inline">\(\hat Y_{\mathrm{CV}}\)</span>. In fact, <span class="math display">\[
\mathrm{Var}(\hat Y_{\mathrm{CV}})
= \mathrm{Var}(\bar Y) \;\bigl(1 - \rho_{Y,X}^2\bigr),
\]</span> where <span class="math inline">\(\rho_{Y,X}\)</span> is the correlation between <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span>. And hence, the closer <span class="math inline">\(\rho_{Y,X}\)</span> is to <span class="math inline">\(\pm1\)</span>, the greater the variance reduction.</p>
<blockquote class="blockquote">
<p>💡 By “borrowing” the known mean of <span class="math inline">\(X\)</span> to correct <span class="math inline">\(\bar Y\)</span>, we project out the component of randomness in <span class="math inline">\(Y\)</span> that <span class="math inline">\(X\)</span> explains — just like using a GPS to recalibrate your wandering path.</p>
</blockquote>
<p>Applying Control Variates to our simple example of estimating rare event with <span class="math inline">\(n = 10^3\)</span>, we get the following estimates:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Control Variate estimate: 0.003202714 
Sampling variance: 0.002912313 </code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>With just <span class="math inline">\(n = 10^3\)</span>, Control Variates tames our wild baseline: the estimate shrinks from 0.005 to about 0.0032 (closer to the true 0.00235), and variance plunges from ≈0.00498 to ≈0.00291 — a roughly 40% variance cut without begging for more samples. Who knew a sidekick variable could pack such a punch?</p>
</blockquote>
<p>Below, we repeat our sample‑size sweep with control variates in play.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="variance_reduction_files/figure-html/plot_control-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>What we observe?</p>
<ol type="1">
<li><em>Noticeable CI tightening at small <span class="math inline">\(n\)</span></em>: Control Variates provide a meaningful improvement of the confidence interval starting from <span class="math inline">\(n = 10^3\)</span>. However, the band is still too wide, considering that we trying to estimate as low probability as 0.0002.</li>
<li><em>Diminishing returns at high <span class="math inline">\(n\)</span></em>: As <span class="math inline">\(n\)</span> grows to <span class="math inline">\(5 × 10^5\)</span> and beyond, the estimates converge toward the true value and their CIs overlap so closely that the practical difference becomes marginal. The real benefit of Control Variates (as it is for Auxiliary Variables as well) is most apparent in low- to moderate‑<span class="math inline">\(n\)</span> regimes.</li>
</ol>
<blockquote class="blockquote">
<p><strong>Bottom Line</strong>: Control Variates give you a reliable, consistent edge — especially when you can’t afford enormous sample sizes. They shave off a chunk of variance and reduce bias, yet still leave you wrestling with wide intervals until <span class="math inline">\(n\)</span> gets large.</p>
</blockquote>
</section>
<section id="importance-sampling" class="level3">
<h3 class="anchored" data-anchor-id="importance-sampling">3.4 Importance Sampling</h3>
<p>Finally let’s talk about my personal favourite - Importance Sampling!</p>
<p><strong>How it works:</strong></p>
<p>When the event you care about is rare under your original distribution <span class="math inline">\(p\)</span>, you end up squandering samples on “unimportant” regions.</p>
<p>Importance Sampling fixes this by <strong>sampling from a different distribution</strong> <span class="math inline">\(q(x)\)</span> that <strong>over‑samples</strong> the critical region (e.g.&nbsp;the tail), and then <strong>reweights</strong> those draws to keep the estimator unbiased.</p>
<p>Concretely, to estimate <span class="math display">\[
p \;=\; \mathbb{E}_p\bigl[\mathbf{1}\{Z &gt; 4\}\bigr]
= \int \mathbf{1}\{z &gt; 4\}\,p(z)\,dz,
\]</span> we instead draw <span class="math inline">\(Z_i \sim q(z)\)</span> (for example, <span class="math inline">\(q\)</span> could be a normal shifted to mean 2 so that more draws exceed 4) and compute the weighted estimator as</p>
<p><span class="math display">\[
\hat p_{\mathrm{IS}}
= \frac{1}{n} \sum_{i=1}^n \mathbf{1}\{Z_i &gt; 4\}\,\frac{p(Z_i)}{q(Z_i)}.
\]</span></p>
<p>Here:</p>
<ul>
<li><span class="math inline">\(\mathbf{1}\{Z_i &gt; 4\}\)</span> flags whether the sample falls in the rare tail.</li>
<li>the <strong>importance weight</strong> <span class="math inline">\(w_i = \frac{p(Z_i)}{q(Z_i)}\)</span> then corrects for the fact that we over‑sampled from <span class="math inline">\(q\)</span> instead of <span class="math inline">\(p\)</span>.</li>
</ul>
<p>Because we draw many more <span class="math inline">\(Z_i\)</span> in the region where <span class="math inline">\(\mathbf{1}\{Z_i&gt;4\}=1\)</span>, our variance <span class="math inline">\(\mathrm{Var}(\hat p_{\mathrm{IS}}) = \frac{1}{n} \,\mathrm{Var}_q\Bigl[\mathbf{1}\{Z&gt;4\}\,\tfrac{p(Z)}{q(Z)}\Bigr]\)</span> can be dramatically lower than <span class="math inline">\(\mathrm{Var}(\hat p_{\mathrm{MC}})\)</span>, especially if <span class="math inline">\(q\)</span> is chosen to closely match the shape of the integrand.</p>
<p>Since our rare event depends on <span class="math inline">\(S = Z_1 + Z_2 \sim N(0,2),\)</span> we choose an importance proposal <span class="math inline">\(q(s) = \mathcal{N}\bigl(\mu_{\rm shift},\,2\bigr)\)</span></p>
<p>This shifts more samples into the tail <span class="math inline">\(s&gt;4\)</span>, and we correct for the change of measure by weighting each draw. Thus, we get the following estimates:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Importance Sampling estimate: 0.002303165 
Sampling variance: 7.14498e-05 </code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>With <span class="math inline">\(n = 10^3\)</span>, Importance Sampling delivers an estimate <span class="math inline">\(\hat p_{\rm IS} = 0.0023\)</span>, and slashes the sampling variance to <span class="math inline">\(7.14\times10^{-5}\)</span>. That’s more than a <strong>100×</strong> reduction in variance compared to standard Monte Carlo at the same sample size <span class="math inline">\(n\)</span> — proof that smart sampling trumps brute force.</p>
</blockquote>
<p>Let’s sweep through sample sizes again and watch how quickly Importance Sampling homes in on <span class="math inline">\(p\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="variance_reduction_files/figure-html/plot_importance-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the Importance Sampling plot we observe:</p>
<ol type="1">
<li><em>Pinpoint CIs at low <span class="math inline">\(n\)</span></em>: at <span class="math inline">\(n=10^3\)</span>, the 95% interval is roughly %[0.0015,0.0025] — essentially a hair’s breadth around 0.00235.</li>
<li><em>Rapid stabilisation</em>: by <span class="math inline">\(n=5\times10^4\)</span>, the error bars have all but vanished.</li>
<li><em>Consistent unbiasedness</em>: all point estimates cluster tightly on the dashed “True p” line, confirming minimal bias.</li>
<li><em>Massive efficiency gains</em>: for the same level of precision, Importance Sampling needs about <strong>100× fewer samples</strong> than standard Monte Carlo — translating directly into massive savings in CPU time and cost.</li>
</ol>
<blockquote class="blockquote">
<p><strong>Bottom Line</strong>: Importance Sampling is the heavyweight champion of variance reduction. By zeroing in on the “important” parts of the distribution, it achieves razor‑sharp precision with a fraction of the simulations required by any other method.</p>
</blockquote>
</section>
<section id="final-sidebyside-comparison" class="level3">
<h3 class="anchored" data-anchor-id="final-sidebyside-comparison">4.1 Final Side‑by‑Side Comparison 🥊</h3>
<p>Let’s line up our three champions against the baseline, now including approximate compute times for <span class="math inline">\(n = 10^3\)</span> simulations:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Sampling Variances and Approximate Compute Times</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Method</th>
<th style="text-align: right;">Variance</th>
<th style="text-align: right;">Time_s</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Standard MC</td>
<td style="text-align: right;">0.00497998</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Antithetic Sampling</td>
<td style="text-align: right;">0.00149249</td>
<td style="text-align: right;">0.002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Control Variates</td>
<td style="text-align: right;">0.00291231</td>
<td style="text-align: right;">0.003</td>
</tr>
<tr class="even">
<td style="text-align: left;">Importance Sampling</td>
<td style="text-align: right;">0.00007145</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody>
</table>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Notes on the approximate compute time</strong></p>
</blockquote>
<blockquote class="blockquote">
<ul>
<li><strong>Standard MC</strong> zips through 1 000 draws in the blink of an eye—our “zero-cost” baseline.</li>
<li><strong>Antithetic Sampling</strong> tacks on a trivial pairing step (just a couple more milliseconds) yet shaves off ~50 % of your variance—like getting a free precision upgrade.</li>
<li><strong>Control Variates</strong> spends slightly more time as Antithetic and provides almost the same variance.</li>
<li><strong>Importance Sampling</strong>, our heavyweight variance-slayer, finishes just as fast as Standard MC here — because calculating and applying importance weights is almost as cheap as drawing a random number.</li>
</ul>
</blockquote>
<p>In other words, each of our variance-reduction champions brings serious precision improvements. So you are free to pick your tool based on your problem’s needs!</p>
</section>
<section id="final-takeaways" class="level3">
<h3 class="anchored" data-anchor-id="final-takeaways">4.2 Final Takeaways</h3>
<p>Not to be annoying, but let’s recap what we have learnt today.</p>
<p>Below is a quick reference for each technique—what it does best, its cost, and when you should reach for it in your own MCMC workflows.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Quick Reference: Variance-Reduction Techniques for MCMC</caption>
<colgroup>
<col style="width: 9%">
<col style="width: 25%">
<col style="width: 13%">
<col style="width: 6%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Technique</th>
<th style="text-align: left;">Key Idea</th>
<th style="text-align: left;">Variance Reduction</th>
<th style="text-align: left;">Compute Cost</th>
<th style="text-align: left;">When to Use</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Standard MC</td>
<td style="text-align: left;">Pure random sampling</td>
<td style="text-align: left;">Baseline (<span class="math inline">\(O(1/√n)\)</span>)</td>
<td style="text-align: left;">Lowest</td>
<td style="text-align: left;">Any problem as a sanity check or when variance is low and analytic tricks aren’t available.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Antithetic Sampling</td>
<td style="text-align: left;">Pair samples with their “mirror” (<span class="math inline">\(U\)</span> vs.&nbsp;<span class="math inline">\((1−U)\)</span>)</td>
<td style="text-align: left;"><strong>more then 50%</strong> reduction</td>
<td style="text-align: left;">+20%</td>
<td style="text-align: left;">When your simulator is cheap and you can naturally generate opposites (<span class="math inline">\(U\)</span> vs.<span class="math inline">\((1−U)\)</span>).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Control Variates</td>
<td style="text-align: left;">Regress out a known-mean auxiliary <span class="math inline">\(X\)</span></td>
<td style="text-align: left;"><strong>more then 50</strong> reduction</td>
<td style="text-align: left;">+30%</td>
<td style="text-align: left;">When you have a strongly correlated control whose expectation you can compute.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Importance Sampling</td>
<td style="text-align: left;">Over-sample important regions and reweight</td>
<td style="text-align: left;"><strong>&gt; 100×</strong> reduction</td>
<td style="text-align: left;">Lowest</td>
<td style="text-align: left;">When targeting very rare events or tail regions and you <strong>can design a good proposal <span class="math inline">\(q\)</span></strong>.</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Armed with these techniques, you’ll turn Monte Chaos into Monte Calm—delivering high-precision estimates with far fewer simulations.</p>
</section>
<section id="wrapping-up" class="level3">
<h3 class="anchored" data-anchor-id="wrapping-up">5. Wrapping up</h3>
<p>If you’ve made it this far, give this tutorial a 👍 and let me know where to point our variance-reduction superpowers next. Here are a few real-world arenas begging for Monte Calm:</p>
<blockquote class="blockquote">
<p><strong>Bootstrapped Value‑at‑Risk</strong>: Tame financial tail-risks on historical returns using antithetic pairs, control variates, and importance sampling—because nothing says “fun Friday night” like plotting confidence bands for losses!</p>
</blockquote>
<p>or</p>
<blockquote class="blockquote">
<p><strong>Big‑Data Approximate Queries</strong>: On a platform like Spotify, estimate the “skip rate” within the first 30 seconds across <strong>hundreds of millions</strong> of streams <strong>by stratified subsampling</strong> — grouping by user region and track popularity tiers — so you can produce tight confidence intervals on your skip metrics without processing every single play log.</p>
</blockquote>
<p>or</p>
<blockquote class="blockquote">
<p>suggest your own wild application in our Slack channel!</p>
</blockquote>
<p>Drop a comment to vote for your favourite next topic, and we’ll crank up the randomness (in a good way) on a real-world problem of your choice!</p>
<p>*If you’re curious about the back-end code and the functions powering these variance-reduction techniques, check out the full project repository on <a href="https://github.com/kkquest/mc-tutorial-R">GitHub</a></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>